-- ============================================================================
-- IndiaWalls AI Calling System — Supabase PostgreSQL Schema
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
-- ============================================================================

-- 1. Calls Table
CREATE TABLE IF NOT EXISTS calls (
    id TEXT PRIMARY KEY,
    call_sid TEXT,
    channel TEXT NOT NULL DEFAULT 'exotel',
    from_number TEXT NOT NULL DEFAULT 'Unknown',
    to_number TEXT DEFAULT '',
    start_time TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    end_time TIMESTAMPTZ,
    duration_seconds NUMERIC(10, 1) DEFAULT 0.0,
    turn_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'in-progress'
);

-- 2. Call Messages / Transcripts Table
CREATE TABLE IF NOT EXISTS call_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    role TEXT NOT NULL,                  -- 'user' (Caller) or 'assistant' (Priya AI)
    content TEXT NOT NULL,               -- Transcribed user speech or synthesized AI reply
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    latency_ms INTEGER DEFAULT 0
);

-- 3. High-Performance Indices
CREATE INDEX IF NOT EXISTS idx_calls_start_time ON calls (start_time DESC);
CREATE INDEX IF NOT EXISTS idx_calls_from_number ON calls (from_number);
CREATE INDEX IF NOT EXISTS idx_calls_channel ON calls (channel);
CREATE INDEX IF NOT EXISTS idx_messages_call_id ON call_messages (call_id);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON call_messages (timestamp ASC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_messages ENABLE ROW LEVEL SECURITY;

-- 5. Policies allowing anonymous/service read & write for our voice agent API
CREATE POLICY "Allow public read calls" ON calls
    FOR SELECT USING (true);

CREATE POLICY "Allow public insert calls" ON calls
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update calls" ON calls
    FOR UPDATE USING (true);

CREATE POLICY "Allow public delete calls" ON calls
    FOR DELETE USING (true);

CREATE POLICY "Allow public read messages" ON call_messages
    FOR SELECT USING (true);

CREATE POLICY "Allow public insert messages" ON call_messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public delete messages" ON call_messages
    FOR DELETE USING (true);
